// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "FashionsCalculator",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "FashionsCalculator",
            targets: ["AppModule"],
            bundleIdentifier: "gabycamilo.FashionsCalculator",
            teamIdentifier: "ZJ687LFKSB",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Fonts/ArimaMadurai-Black.ttf")
            ]
        )
    ]
)
